 services:
  weaviate-ui: 
    command: uvicorn weaviate_ui.main:app --host 0.0.0.0 --port 7777 --reload
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7777:7777"
    environment:
      - WEAVIATE_HOST=131.145.73.24
      - WEAVIATE_PORT=80
      - WEAVIATE_SECURE=
      - WEAVIATE_GRPC_HOST=4.158.72.252
      - WEAVIATE_GRPC_PORT=50051
      - WEAVIATE_GRPC_SECURE=
      - WEAVIATE_AUTH_CREDENTIALS=2e453774c5b1ee4771153dc440775b8ce5b72826ecb3396adc83c42e1b192fa5
    volumes:
      - ./weaviate_ui:/app/weaviate_ui
      # - ./frontend/dist:/app/static # Uncomment this line if you want to use a local frontend build
