 services:
  weaviate-ui: 
    command: uvicorn weaviate_ui.main:app --host 0.0.0.0 --port 7777 --reload
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Frontend (Vite) MSAL configuration used at build time
        VITE_AZURE_AD_CLIENT_ID: XXX
        VITE_AZURE_AD_TENANT_ID: XXX
        VITE_AUTH_REDIRECT_URI: http://localhost:7777
    ports:
      - "7777:7777"
    environment:
      - WEAVIATE_HOST=XXXXX
      - WEAVIATE_PORT=XX
      - WEAVIATE_SECURE=
      - WEAVIATE_GRPC_HOST=XX
      - WEAVIATE_GRPC_PORT=XXXXX
      - WEAVIATE_GRPC_SECURE=
      - WEAVIATE_AUTH_CREDENTIALS=XXXXXXX
      - AZURE_AD_TENANT_ID=xxx
      - AZURE_AD_CLIENT_ID=XXXX
      - AZURE_AD_AUDIENCE=XXXX
    volumes:
      - ./weaviate_ui:/app/weaviate_ui
      # - ./frontend/dist:/app/static # Uncomment this line if you want to use a local frontend build
