/*
Having the following format:

{
    "Article": {
        "name": "Article",
        "description": null,
        "generative_config": null,
        "properties": [
            {
                "name": "title",
                "description": null,
                "data_type": "text",
                "index_filterable": true,
                "index_range_filters": false,
                "index_searchable": true,
                "nested_properties": null,
                "tokenization": "word",
                "vectorizer_config": null,
                "vectorizer": "none"
            },
            {
                "name": "text",
                "description": null,
                "data_type": "text",
                "index_filterable": true,
                "index_range_filters": false,
                "index_searchable": true,
                "nested_properties": null,
                "tokenization": "word",
                "vectorizer_config": null,
                "vectorizer": "none"
            },
            {
                "name": "url",
                "description": null,
                "data_type": "text",
                "index_filterable": true,
                "index_range_filters": false,
                "index_searchable": true,
                "nested_properties": null,
                "tokenization": "word",
                "vectorizer_config": null,
                "vectorizer": "none"
            },
            {
                "name": "parse_date",
                "description": null,
                "data_type": "date",
                "index_filterable": true,
                "index_range_filters": false,
                "index_searchable": false,
                "nested_properties": null,
                "tokenization": null,
                "vectorizer_config": null,
                "vectorizer": "none"
            },
            {
                "name": "region",
                "description": null,
                "data_type": "text[]",
                "index_filterable": true,
                "index_range_filters": false,
                "index_searchable": true,
                "nested_properties": null,
                "tokenization": "word",
                "vectorizer_config": null,
                "vectorizer": "none"
            },
            {
                "name": "mongo_id",
                "description": "This property was generated by Weaviate's auto-schema feature on Mon Feb  3 10:45:38 2025",
                "data_type": "text",
                "index_filterable": true,
                "index_range_filters": false,
                "index_searchable": true,
                "nested_properties": null,
                "tokenization": "word",
                "vectorizer_config": null,
                "vectorizer": "none"
            }
        ],
        "references": [],
        "reranker_config": null,
        "vectorizer_config": null,
        "vectorizer": null,
        "vector_config": {
            "title_vector": {
                "vectorizer": {
                    "vectorizer": "text2vec-transformers",
                    "model": {
                        "poolingStrategy": "masked_mean",
                        "vectorizeClassName": true
                    },
                    "source_properties": null
                },
                "vector_index_config": {
                    "quantizer": null,
                    "cleanup_interval_seconds": 300,
                    "distance_metric": "cosine",
                    "dynamic_ef_min": 100,
                    "dynamic_ef_max": 500,
                    "dynamic_ef_factor": 8,
                    "ef": -1,
                    "ef_construction": 128,
                    "filter_strategy": "sweeping",
                    "flat_search_cutoff": 40000,
                    "max_connections": 32,
                    "skip": false,
                    "vector_cache_max_objects": 1000000000000
                }
            }
        }
    }
}

The array can have any number of keys with the following format. The value needed in a separate interface so it can be reused.
*/

interface Property {
  name: string;
  description: string | null;
  data_type: string;
  index_filterable: boolean;
  index_range_filters: boolean;
  index_searchable: boolean;
  nested_properties: null;
  tokenization: string | null;
  vectorizer_config: null;
  vectorizer: string;
}

interface VectorizerConfig {
  vectorizer: string;
  model: {
    poolingStrategy: string;
    vectorizeClassName: boolean;
  };
  source_properties: null;
}

interface VectorIndexConfig {
  quantizer: null;
  cleanup_interval_seconds: number;
  distance_metric: string;
  dynamic_ef_min: number;
  dynamic_ef_max: number;
  dynamic_ef_factor: number;
  ef: number;
  ef_construction: number;
  filter_strategy: string;
  flat_search_cutoff: number;
  max_connections: number;
  skip: boolean;
  vector_cache_max_objects: number;
}

interface VectorConfig {
  [key: string]: {
    vectorizer: VectorizerConfig;
    vector_index_config: VectorIndexConfig;
  };
}

interface Collection {
  name: string;
  description: string | null;
  generative_config: null;
  properties: Property[];
  references: any[];
  reranker_config: null;
  vectorizer_config: null;
  vectorizer: null;
  vector_config: VectorConfig;
}

interface Collections {
  [key: string]: Collection;
}

// export all
export type {
  Property,
  VectorizerConfig,
  VectorIndexConfig,
  VectorConfig,
  Collection,
  Collections,
};
